name: Generate SBOM with CycloneDX for .NET

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sbom-generation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}/pkatu-pipeline-assignment/pkatu-pipeline-assignment.csproj

      - name: Build the project
        run: dotnet build ${{ github.workspace }}/pkatu-pipeline-assignment/pkatu-pipeline-assignment.csproj --no-restore

      - name: Install CycloneDX .NET tool
        run: dotnet tool install --global CycloneDX

      - name: Generate CycloneDX BOM
        run: dotnet-CycloneDX ${{ github.workspace }}/pkatu-pipeline-assignment/pkatu-pipeline-assignment.csproj --output ${{ github.workspace }}/pkatu-pipeline-assignment/sbom.xml

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cyclonedx-bom
          path: ${{ github.workspace }}/pkatu-pipeline-assignment/sbom.xml
