name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build_and_test:

    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies and build
      run: |
        dotnet restore ./pkatu-pipeline-assignment.sln
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal

    - name: Create Docker network
      run: docker network create selenium-network

    - name: Build and deploy to myapp
      run: |
         docker build -t pkatu-pipeline-assignment:mytag ./pkatu-pipeline-assignment
         docker stop myapp || true
         docker rm myapp || true   

         docker run -d --net selenium-network -p 8080:80 --name myapp pkatu-pipeline-assignment:mytag
      continue-on-error: true
  

    - name: Check Selenium Server availability
      id: check-selenium
      run: |
          SELENIUM_IP=""
          while [ -z "$SELENIUM_IP" ]; do
          SELENIUM_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' myapp)
          if [ -z "$SELENIUM_IP" ]; then
          echo "Waiting for Selenium server..."
          sleep 5
          fi
          done
          echo "Selenium server is up and running. IP: $SELENIUM_IP"


    - name: Run Selenium Tests
      run: |
        cd ./pkatu-pipeline-assignment  
        npx selenium-side-runner --server http://${SELENIUM_IP}:4444/wd/hub --capabilities browserName=chrome,goog:chromeOptions.args=[--headless,--disable-gpu,--window-size=1920x1080] ./pkatu-pipeline-assignment.side
        needs: check-selenium
