# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify the Node.js version

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - name: Restore dependencies
        run: dotnet restore ./pkatu-pipeline-assignment.sln

      - name: Change directory and Run Snyk to check for vulnerabilities
        run: |
          cd ./pkatu-pipeline-assignment
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  build_and_deploy_docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: actions/checkout@v3 
    - name: Build the Docker image    
      run: docker build . --file pkatu-pipeline-assignment/Dockerfile --tag pkatu-pipeline-assignment:mytag
    - name: Run the Docker image
      run: docker run -d -p 8080:80 pkatu-pipeline-assignment:mytag
    - name: Run Selenium Server
      run: docker run -d -p 4444:4444 selenium/standalone-chrome:latest
  selenium_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Selenium Side Runner
      run: npm install -g selenium-side-runner

    - name: Setup ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium Tests
      run: selenium-side-runner pkatu-pipeline-assignment.side
