name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 
  build_and_test:

    runs-on: ubuntu-latest

    steps:
  
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies and build
      run: |
        dotnet restore ./pkatu-pipeline-assignment.sln
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal

    - name: Create Docker network
      run: docker network create selenium-network

    - name: Check Selenium Server availability
      run: |
        until curl -s http://selenium-server:4444/wd/hub/status | grep -q '"ready":true'; do
        echo "Waiting for Selenium server..."
        sleep 5
        done
        echo "Selenium server is up and running."
        
    - name: Build the Docker image
      run: docker build -t pkatu-pipeline-assignment:mytag ./pkatu-pipeline-assignment

    - name: Get Selenium Server IP
      id: get_selenium_ip
      run: |
        SELENIUM_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' selenium-server)
        echo "Selenium Server IP: $SELENIUM_IP"
      env:
        DOCKER_CLI_AGGREGATE_OUTPUT: 1
    
    - name: Run the Docker image (Application) and Selenium Tests
      run: |
        docker run -d --net selenium-network -p 8080:80 --name myapp pkatu-pipeline-assignment:mytag
        docker pull selenium/standalone-chrome:latest
        docker run -d --net selenium-network --name selenium-server \
        --health-cmd='curl -f http://localhost:4444/wd/hub/status || exit 1' \
        --health-interval=10s --health-timeout=5s --health-retries=3 \
        selenium/standalone-chrome:latest 
        sleep 10  # Wait for Selenium server to start
        cd ./pkatu-pipeline-assignment  # Navigate to the project directory
        npx selenium-side-runner --server http://SELENIUM_SERVER_IP:4444/wd/hub --capabilities browserName=chrome,goog:chromeOptions.args=[--headless,--disable-gpu,--window-size=1920x1080] ./pkatu-pipeline-assignment.side
