name: Snyk Security Scan and SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snyk-scan-and-sbom-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display the current working directory
        run: pwd

        working-directory: pkatu-pipeline-assignment


      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk security scan
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # Set working directory only if the .csproj file is not in the root of the repo
        working-directory: pkatu-pipeline-assignment

      - name: Generate SBOM
        run: snyk iac describe --kind=k8s --output=./sbom-output/sbom.spdx
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # Adjust this if your .csproj is in the nested folder
        working-directory: pkatu-pipeline-assignment

      - name: Upload SBOM as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: pkatu-pipeline-assignment/sbom-output/sbom.spdx
