name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Download OWASP Dependency-Check CLI
        run: curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.2/dependency-check-7.0.2-release.zip

      - name: Unzip OWASP Dependency-Check CLI
        run: unzip dependency-check.zip

      - name: Run OWASP Dependency-Check Scan
        run: ./dependency-check/bin/dependency-check.sh --scan ${{ github.workspace }}/pkatu-pipeline-assignment --out . --format ALL

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: owasp-sbom
          path: dependency-check-report.json
