name: Snyk Security Scan and SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-scan-and-sbom-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if your project is Node.js based)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk authentication
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk security scan
        run: snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Create SBOM output directory
        run: mkdir -p ./sbom-output

      - name: Generate SBOM
        run: snyk iac describe --kind=k8s --output=./sbom-output/sbom.spdx
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SBOM as an Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: ./sbom-output/sbom.spdx
