name: Snyk Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if your project is Node.js based)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk security scan
        run: snyk test --all-projects

      - name: Generate SBOM
        run: snyk iac describe --kind k8s --output=sbom.spdx
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
