name: Snyk Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Restore Dependencies and Build
        run: dotnet restore && dotnet build

      - name: Run Snyk Scan
        run: snyk test --all-projects --json > snyk-report.json

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: snyk-sbom
          path: snyk-report.json
